# GoReleaser configuration
# https://goreleaser.com

version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: gogate
    main: ./cmd/gogate
    binary: gogate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildTime={{.Date}}

archives:
  - id: gogate
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - LICENSE
      - README.md
      - config.example.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

# Note: Docker images are built via the separate Docker job in CI workflow
# This allows us to use our multi-stage Dockerfile with distroless runtime

release:
  draft: false
  prerelease: auto
